"""Application-layer models for host actions and AI results."""

from ai_core.application.models.actions import (
    ActionPlan,
    CreateDocumentInput,
    CreateDocumentOutput,
    HostAction,
    HostActionInput,
    HostActionOutput,
    HostActionPolicy,
    HostActionResult,
    HostActionResultType,
    HostActionStatus,
    HostActionType,
    LinkDocumentsInput,
    LinkDocumentsOutput,
    MoveDocumentInput,
    MoveDocumentOutput,
    UpdateDocumentInput,
    UpdateDocumentOutput,
)
from ai_core.application.models.llm import LLMMessage
from ai_core.application.models.queries import AIQuery, QueryAnchor, RequestContext, SearchScope
from ai_core.application.models.results import (
    AssistantClarification,
    AssistantResponse,
    AssistantResponseStatus,
    DocumentRecommendation,
    DocumentRecommendationResult,
    DraftResult,
    FolderRecommendation,
    FolderRecommendationResult,
    GeneratedTextResult,
    RelatedRecommendationItem,
    RelatedRecommendationResult,
)
from ai_core.application.models.retrieval import (
    FolderRetrievalResult,
    RelatedRetrievalItem,
    RelatedRetrievalResult,
    RetrievalResult,
)
from ai_core.application.models.tasks import (
    TaskAnalysis,
    TaskDecision,
    TaskDecisionType,
    TaskEvent,
    TaskEventType,
    TaskOutput,
    TaskOutputResult,
    TaskOutputType,
    TaskRequest,
    TaskSnapshot,
    TaskStatus,
)

__all__ = [
    "ActionPlan",
    "AIQuery",
    "AssistantClarification",
    "AssistantResponse",
    "AssistantResponseStatus",
    "CreateDocumentInput",
    "CreateDocumentOutput",
    "DocumentRecommendation",
    "DocumentRecommendationResult",
    "DraftResult",
    "FolderRecommendation",
    "FolderRecommendationResult",
    "FolderRetrievalResult",
    "GeneratedTextResult",
    "HostAction",
    "HostActionInput",
    "HostActionOutput",
    "HostActionPolicy",
    "HostActionResult",
    "HostActionResultType",
    "HostActionStatus",
    "HostActionType",
    "LinkDocumentsInput",
    "LinkDocumentsOutput",
    "LLMMessage",
    "MoveDocumentInput",
    "MoveDocumentOutput",
    "QueryAnchor",
    "RelatedRecommendationItem",
    "RelatedRecommendationResult",
    "RelatedRetrievalItem",
    "RelatedRetrievalResult",
    "RequestContext",
    "RetrievalResult",
    "SearchScope",
    "TaskAnalysis",
    "TaskDecision",
    "TaskDecisionType",
    "TaskEvent",
    "TaskEventType",
    "TaskOutput",
    "TaskOutputResult",
    "TaskOutputType",
    "TaskRequest",
    "TaskSnapshot",
    "TaskStatus",
    "UpdateDocumentInput",
    "UpdateDocumentOutput",
]
